export enum OutcomingEvents {
  PLAYER_JOINED = "PLAYER_JOINED",
  GAME_STARTED = "GAME_STARTED",
  SEND_UNITS = "SEND_UNITS",
  GAME_END = "GAME_END",
  SYNC = "SYNC",
  GAME_CREATED = "GAME_CREATED",
  WON = "WON",
  LOST = "LOST",
}
