const MAP_W = 50
const MAP_H = 20

const PLANET_D_MAX_DIVISOR = 3
const PLANET_D_MIN_DIVISOR = 24

const PLANET_STARTER_D      = 2
const PLANET_STARTER_HEALTH = 3 

const ATTEMPTS = 10

const MAX_HEALTH = 50
const MIN_HEALTH = 10

// const PLANET_DISTANCE_MIN = 

const PLANET_N_MIN = 6
const PLANET_N_MAX = 14

const PLAYER_COUNT = 2

export { 
  MAP_H, 
  MAP_W, 
  PLANET_D_MAX_DIVISOR, 
  PLANET_D_MIN_DIVISOR, 
  ATTEMPTS,
  PLANET_STARTER_D,
  PLANET_STARTER_HEALTH,
  MAX_HEALTH,
  MIN_HEALTH,
  PLANET_N_MAX,
  PLANET_N_MIN,
  PLAYER_COUNT
}